CREATE TABLE BOOK (
    BOOKID NUMBER CONSTRAINT BOOK_PK PRIMARY KEY,
    BOOKNAME VARCHAR2(200),
    PUBLISHER VARCHAR(200),
    PRICE NUMBER);

SELECT * FROM BOOK;

CREATE TABLE ORDERS (
    ORDERID NUMBER CONSTRAINT ORDER_PK PRIMARY KEY,
    CUSTID NUMBER,
    BOOKID NUMBER,
    SALEPRICE NUMBER,
    ORDERDATE DATE
);

SELECT * FROM ORDERS;

CREATE TABLE CUSTOMER (
    CUSTID NUMBER CONSTRAINT CUSTOMER_PK PRIMARY KEY,
    NAME VARCHAR(50),
    ADDRESS VARCHAR(200),
    PHONE VARCHAR(13)
);

SELECT * FROM CUSTOMER;

--시퀀스(SEQUENCE) : 
CREATE SEQUENCE SEQ_BOOK --시퀀스 생성
INCREMENT BY 1 --증감값
START WITH 1 --시작값
NOCYCLE --최대값 도달 후 시퀀스 생성 중단
NOCACHE; --캐시에 저장하지 않음.

CREATE SEQUENCE SEQ_ORDERS
INCREMENT BY 1 
START WITH 1 
NOCYCLE 
NOCACHE; 

CREATE SEQUENCE  SEQ_CUSTOMER
INCREMENT BY 1 
START WITH 1 
NOCYCLE 
NOCACHE;

INSERT INTO BOOK VALUES(SEQ_BOOK.NEXTVAL, '컴퓨터의 역사', '아이티', 7000);
INSERT INTO BOOK VALUES(SEQ_BOOK.NEXTVAL, '컴퓨터는 무엇일까', '굿북', 13000);
INSERT INTO BOOK VALUES(SEQ_BOOK.NEXTVAL, '컴퓨터의 이해', '이젠', 22000);
INSERT INTO BOOK VALUES(SEQ_BOOK.NEXTVAL, '자바 이론', '이젠', 35000);
INSERT INTO BOOK VALUES(SEQ_BOOK.NEXTVAL, '데이터베이스 교본', '아이티', 8000);
INSERT INTO BOOK VALUES(SEQ_BOOK.NEXTVAL, 'HTML 기술', '아이티', 6000);
INSERT INTO BOOK VALUES(SEQ_BOOK.NEXTVAL, '스프링의 개념', '에비씨미디어', 20000);
INSERT INTO BOOK VALUES(SEQ_BOOK.NEXTVAL, '스프링을 부탁해', '에비씨빛미디어', 13000);
INSERT INTO BOOK VALUES(SEQ_BOOK.NEXTVAL, '파이썬 이야기', '코딩빔', 7500);
INSERT INTO BOOK VALUES(SEQ_BOOK.NEXTVAL, 'python story', 'Pearson', 13000);

SELECT * FROM BOOK;

INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, '박건우', '인천시 송도', '010-1111-2222');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, '김선해', '서울시 종로구', '010-2111-2222');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, '장지혜', '서울시 용산구', '010-3111-2222');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, '추오섭', '경기도 의정부', '010-4111-2222');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, '박승철', '서울시 마포구', NULL);

SELECT * FROM CUSTOMER;

INSERT INTO ORDERS VALUES (SEQ_ORDERS.NEXTVAL, 1, 1, 6000, '2022-05-01');
INSERT INTO ORDERS VALUES (SEQ_ORDERS.NEXTVAL, 1, 3, 21000, '2022-05-03');
INSERT INTO ORDERS VALUES (SEQ_ORDERS.NEXTVAL, 2, 5, 8000, '2022-05-03');
INSERT INTO ORDERS VALUES (SEQ_ORDERS.NEXTVAL, 3, 6, 6000, '2022-05-04');
INSERT INTO ORDERS VALUES (SEQ_ORDERS.NEXTVAL, 4, 7, 20000, '2022-05-05');
INSERT INTO ORDERS VALUES (SEQ_ORDERS.NEXTVAL, 1, 2, 12000, '2022-05-07');
INSERT INTO ORDERS VALUES (SEQ_ORDERS.NEXTVAL, 4, 8, 13000, '2022-05-07');
INSERT INTO ORDERS VALUES (SEQ_ORDERS.NEXTVAL, 3, 10, 12000, '2022-05-08');
INSERT INTO ORDERS VALUES (SEQ_ORDERS.NEXTVAL, 2, 10, 7000, '2022-05-09');
INSERT INTO ORDERS VALUES (SEQ_ORDERS.NEXTVAL, 3, 8, 13000, '2022-05-10');

SELECT * FROM ORDERS;